const Routes = {
  LOADING: 'LOADING',

  LOGIN_STACK: 'LOGIN_STACK',
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  SINGUP_SCREEN: 'SINGUP_SCREEN',
  FORGOT_SCREEN: 'FORGOT_SCREEN',
  OTP_SCREEN: 'OTP_SCREEN',
  RESET_PASSWORD: 'RESET_PASSWORD',
  CONGRATULATIONS_SCREEN: 'CONGRATULATIONS_SCREEN',
  MAIN_APP: 'MAIN_APP', //DRAWER

  APP_INTRO: 'APP_INTRO',

  HOME_STACK: 'HOME_STACK', // HOMESTACK CONTAINER FOR TABS
  HOME_TABS: 'HOME_TABS', //HOME TABS

  HOME_SCREEN: 'HOME',

  TASK_SCREEN: 'TASK_SCREEN',
  TASK_READING: 'TASK_READING',
  TASK_VOCABULARY: 'TASK_VOCABULARY',
  TASK_LISTENING: 'TASK_LISTENING',
  TASK_SPEAKING: 'TASK_SPEAKING',

  FLASH_CARD: 'FLASH_CARD',

  Account_SCREEN: 'ACCOUNT',
  SETTING_SCREEN: 'SETTING',
  NOTIFICATION_SCREEN: 'NOTIFICATIONS',
  PERSONAL_INFO: 'PERSONAL_INFO',
  ABOUT_SCREEN: 'ABOUT_SCREEN',

  LANGUAGE_SET: 'LANGUAGE_SET',
  WHY_STUDY: 'WHY_STUDY',
  SELECT_LEVEL: 'SELECT_LEVEL',
  COMPLETE_INTRO: 'COMPLETE_INTRO',
};

export default Routes;
